config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: :show
  
  resources :tests, controller: :exams, as: :exams do
    member do
      get 'begin', as: :begin
      get 'complete', as: :complete
      get 'category_reports', as: :category_reports
    end
    resources :questions
    resources :category_scores, only: [:create, :update]
    resources :categories do 
      resources :category_reports
    end
  end

  resources :accounts, except: [:index, :show]

  root 'static_pages#home'
  
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/help'

end

app/models/category_report.rb
# == Schema Information
#
# Table name: category_reports
#
#  id          :integer          not null, primary key
#  category_id :integer
#  text        :text
#  created_at  :datetime
#  updated_at  :datetime
#  value_min   :integer
#  value_max   :integer
#

class CategoryReport < ActiveRecord::Base
  belongs_to :category

  validates_presence_of :text, :category
end

app/controllers/category_reports_controller.rb
# == Schema Information
#
# Table name: category_reports
#
#  id          :integer          not null, primary key
#  category_id :integer
#  text        :text
#  created_at  :datetime
#  updated_at  :datetime
#  value_min   :integer
#  value_max   :integer
#

class CategoryReportsController < ApplicationController
  before_action :set_category_report, only: [:show, :edit, :update, :destroy]

  # GET /category_reports
  # GET /category_reports.json
  def index
    @category = Category.includes(:category_reports, :exam).find_by(id: params[:category_id])
    @category_reports = @category.category_reports.order("value_min asc")
  end

  # GET /category_reports/1
  # GET /category_reports/1.json
  def show
  end

  # GET /category_reports/new
  def new
    @category_report = CategoryReport.new
    set_exam_and_category
    @value_max = params[:value_max] || @category.find_value_max
    @value_min = params[:value_min] || @category.find_remaining_value_min
  end

  # GET /category_reports/1/edit
  def edit
    @value_max = @category_report.value_max
    @value_min = @category_report.value_min
  end

  # POST /category_reports
  # POST /category_reports.json
  def create
    @category_report = CategoryReport.new(category_report_params)
    set_exam_and_category
    @category_report.category = @category 
    @value_max = @category.find_value_max

    if @category_report.save
      if @category.find_remaining_value_min == @value_max
        # Go back to the list of categories if all reports have been created for this category
        @category.reports_complete = true
        @category.save!
        redirect_to category_reports_exam_path(@exam), notice: "All reports for category #{@category.name} have been created successfully"
      else
        # Go back to another new report form for this category if not all values have been covered
        redirect_to new_exam_category_category_report_path(@exam, @category, value_min: @category_report.value_max + 1, value_max: @value_max), notice: "Category report created successfully"
      end
    else
      @value_min = @category.find_remaining_value_min
      render :new
    end
  end

  # PATCH/PUT /category_reports/1
  # PATCH/PUT /category_reports/1.json
  def update
    if @category_report.update(category_report_params)
      redirect_to exam_category_category_reports_path(@exam, @category), notice: "Your report was successfully updated."
    else
      @value_min = @category_report.value_min
      @value_max = @category_report.value_max
      render :edit
    end
  end

  # DELETE /category_reports/1
  # DELETE /category_reports/1.json
  def destroy
    @category_report.destroy
    respond_to do |format|
      format.html { redirect_to category_reports_url, notice: 'Category report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category_report
      @category_report = CategoryReport.find(params[:id])
      set_exam_and_category
    end

    def set_exam_and_category
      @exam = Exam.includes(:categories, :questions, :answers).find_by(id: params[:exam_id])
      @category = @exam.categories.find_by(id: params[:category_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_report_params
      params.require(:category_report).permit(:text, :value_max, :value_min)
    end
end

app/helpers/category_reports_helper.rb
# == Schema Information
#
# Table name: category_reports
#
#  id          :integer          not null, primary key
#  category_id :integer
#  text        :text
#  created_at  :datetime
#  updated_at  :datetime
#  value_min   :integer
#  value_max   :integer
#

module CategoryReportsHelper
end

app/views/category_reports/_form.html.erb
<div class="row" >
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for([@exam, @category, @category_report]) do |f| %>
      <% if @category_report.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@category_report.errors.count, "error") %> prohibited this category_report from being saved:</h2>

          <ul>
          <% @category_report.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <strong>Minimum value for this report: <%= @value_min %></strong>
        <%= f.hidden_field(:value_min, value: @value_min) %>
      </div>

      <div class="form-group">
        <% if params[:action] == "edit" %>
          <strong>Maximum value for this report: <%= @value_max %></strong>
        <% else %>
          <%= f.label :value_max, "Maximum value for this report: " %>
          <%= f.number_field :value_max, autofocus: true, min: @value_min, max: @value_max, class: "form-control" %>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :text, "Report for this range of values:" %>
        <%= f.text_area :text, autofocus: true, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit @category_report.new_record? ? "Next" : "Update", class: "btn btn-lg btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/category_reports/edit.html.erb
<%= provide(:title, "Edit - Results Reports for #{@category.name}") %>

<h1>Editing report for <%= @category.name %></h1>

<%= render 'form' %>

app/views/category_reports/index.html.erb
<%= provide(:title, "Edit - #{@category.name} Reports") %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <h1>Category reports for <%= @category.name %></h1>
    <h4></h4>
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="col-xs-2">Min Value</th>
          <th class="col-xs-2">Max Value</th>
          <th class="col-xs-8">Text</th>
        </tr>
      </thead>
      <tbody>
        <% @category_reports.each do |report| %>
          <tr>
            <td><%= report.value_min %></td>
            <td><%= report.value_max %></td>
            <td><%= link_to truncate(report.text), edit_exam_category_category_report_path(@category.exam, @category, report) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/category_reports/new.html.erb
<%= provide(:title, "Results Reports for #{@category.name}") %>

<h1>New Category Report for <%= @category.name %></h1>

<p>This category needs reports for results ranging from <%= @value_min %> to <%= @value_max %></p>

<%= render 'form' %>

app/views/category_reports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_report_path(@category_report) %> |
<%= link_to 'Back', category_reports_path %>