config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: :show
  
  resources :tests, controller: :exams, as: :exams do
    member do
      get 'begin', as: :begin
      get 'complete', as: :complete
      get 'category_reports', as: :category_reports
    end
    resources :questions
    resources :category_scores, only: [:create, :update]
    resources :categories do 
      resources :category_reports
    end
  end

  resources :accounts, except: [:index, :show]

  root 'static_pages#home'
  
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/help'

end

app/models/exam.rb
# == Schema Information
#
# Table name: exams
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  account_id  :integer
#  exam_type   :string(255)
#

class Exam < ActiveRecord::Base
  belongs_to :account
  has_many :scores, dependent: :destroy
  has_many :users, through: :scores
  has_many :reports, dependent: :destroy 
  has_many :categories
  has_many :questions, dependent: :destroy
  has_many :answers, through: :questions
  
  EXAM_TYPES = ["multiple_choice", "long_answer", "mixed"]

  validates_presence_of :account
  validates :exam_type, presence: true, inclusion: { in: EXAM_TYPES }
  validates :name, presence: true, length: { in: 4..50 }
  validates :description, :presence => true

  def multiple_choice?
    self.exam_type == "multiple_choice"
  end

  def long_answer?
    self.exam_type == "long_answer"
  end

  def includes_multiple_choice?
    self.exam_type != "long_answer"
  end
end

app/controllers/exams_controller.rb
# == Schema Information
#
# Table name: exams
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  account_id  :integer
#  exam_type   :string(255)
#

class ExamsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :begin, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @exams = Exam.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
    @exam = Exam.includes(:questions, :answers).where(id: params[:id]).first
  end

  # GET /tests/new
  def new
    @exam = Exam.new
  end

  # GET /tests/1/edit
  def edit
    @exam = Exam.find(params[:id])
  end

  def category_reports
    @exam = Exam.includes(:categories).find_by(id: params[:id])
  end

  # GET /tests/1/begin
  def begin
    @exam = Exam.includes(:questions).find_by(id: params[:id])
    score = Score.find_by(user: current_user, exam: @exam)
    score ||= Score.create(user: current_user, exam: @exam)
    questions = @exam.questions.order(:created_at)
    unless score.questions_answered == questions.length
      redirect_to exam_question_url(@exam, questions[score.questions_answered])
    else
      redirect_to complete_exam_url(@exam)
    end
  end

  def complete
    @exam = Exam.find(params[:id])
  end

  # POST /tests
  # POST /tests.json
  def create
    @exam = Exam.new(exam_params)
    @exam.account = current_user.account

    respond_to do |format|
      if @exam.save
        format.html { redirect_to new_exam_question_path(@exam), notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    @exam = Exam.find(params[:id])
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @exam = Exam.find(params[:id])
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:name, :description, :exam_type)
    end
end

app/helpers/exams_helper.rb
# == Schema Information
#
# Table name: exams
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  account_id  :integer
#  exam_type   :string(255)
#

module ExamsHelper
end

app/views/exams/_form.html.erb
<div class="jumbotron writing no-padding">
  <div class="container">
  </div>
</div>

<div class="row">
  <div class="well col-sm-8 col-md-offset-2">

    <h2>Create Test</h2>

    <%= form_for(@exam) do |f| %>

      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :exam_type, "Type of test" %><br>
        <%= f.select :exam_type, options_for_select([["Multiple choice", "multiple_choice"], ["Long answer", "long_answer"]], "multiple_choice"), {}, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Next", class: "btn btn-success btn-lg col-xs-12" %>
      </div>
    <% end %>

  </div>
</div>

app/views/exams/category_reports.html.erb
<%= provide(:title, "Category Results") %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <h1>Creating Results Reports</h1>
    <p>You will need to create results reports for each category in your test. We will calculate the total possible range of scores for each category, and you can create however many reports you'd like for that category, as long as there is a report for each possible score. After a test taker completes a test, they will receive an assembled report composed of each of their category reports.</p>
    <p><strong>To begin, select a category below:</strong></p>
    <ul>
      <!-- Will need to deactivate links for categories that already have reports. Will need to add a field to categories that indicates whether or not all of its reports have been created. After the link is deactivated, add an "edit" link that can be used to change it. After all categories have all reports, enable a "Next" button. -->
      <% @exam.categories.order("name asc").each do |category| %>
        <% if category.reports_complete %>
          <li><%= category.name %> (complete) | <%= link_to "edit", exam_category_category_reports_path(@exam, category) %></li>
        <% else %>
          <li><%= link_to category.name, new_exam_category_category_report_path(@exam, category) %></li>
        <% end %>
      <% end %>
    </ul> 
    <% if @exam.categories.select { |category| !category.reports_complete }.empty? %>
      <%= link_to "Next", "#", class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>
</div>

app/views/exams/complete.html.erb
<%= provide(:title, "Test Complete") %>

<div class="row">
  <div class="well col-sm-12 col-md-8 col-md-offset-2">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><h1>Congratulations!</h1></th>
        </tr>
        <tr>
          <th><h2> You've completed the test <strong><%= @exam.name %></h2></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <%= link_to "See results", '#', class: "btn btn-lg btn-success" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/exams/edit.html.erb
<h1>Editing exam</h1>

<%= render 'form' %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<%= provide(:title, "Tests") %>

<div class="jumbotron writing no-padding">
  <div class="container">
  </div>
</div>

<h1>Tests</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="col-md-3">Name</th>
      <th class="col-md-9">Description</th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= link_to exam.name, exam %></td>
        <td><%= truncate(exam.description, length: 250) %> <%= link_to "more", exam %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

Have an idea? <%= link_to 'Create your own test.', new_exam_path %>

app/views/exams/new.html.erb
<%= provide(:title, "Create a Test") %>

<%= render 'form' %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<%= provide(:title, @exam.name) %>

<div class="jumbotron writing no-padding">
  <div class="container">
  </div>
</div>

<div class="row">
  <div class="well col-sm-8 col-md-offset-2">
    <p id="notice"><%= notice %></p>

    <table class="table table-striped">
      <thead>
        <tr>
          <th class="col-sm-8">
            From: <%= @exam.account.name %>
          </th>
          <th class="col-sm-4"></th>
        </tr>
        <tr>
          <th class="col-sm-9">
            <span class="exam-name"><%= @exam.name %></span>
          </th>
          <th class="col-sm-3"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <%= @exam.description %>
          </td>
        </tr>
        <tr>
          <td>Number of questions: <%= @exam.questions.count %></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td>
            <%= link_to 'Take this test', begin_exam_path(@exam), class: "btn btn-lg btn-primary" %>
          </td>
        </tr>
      </tbody>
    </table>

  </div>
</div>