config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: :show
  
  resources :tests, controller: :exams, as: :exams do
    member do
      get 'begin', as: :begin
      get 'complete', as: :complete
      get 'category_reports', as: :category_reports
    end
    resources :questions
    resources :category_scores, only: [:create, :update]
    resources :categories do 
      resources :category_reports
    end
  end

  resources :accounts, except: [:index, :show]

  root 'static_pages#home'
  
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/help'

end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  subdomain  :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Account < ActiveRecord::Base
  before_save { self.subdomain.downcase! }
  
  belongs_to :user
  has_many :exams, dependent: :destroy

  validates_presence_of :user
  validates :name, presence: true, uniqueness: true
  validates :subdomain, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9\-_]+\Z/, 
            :message => "only allows letters, numbers, dashes and underscores. Does not allow spaces." }
end

app/controllers/accounts_controller.rb
# == Schema Information
#
# Table name: accounts
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  subdomain  :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: [:edit, :update]

  def new
    @account = Account.new
    @creating_test = params[:creating_test] ? true : false
  end

  def edit
  end

  def create
    @account = Account.new(account_params)
    @account.user = current_user

    if @account.save
      flash[:notice] = "Congrats! #{@account.subdomain} is now your subdomain."
      if params[:creating_test]
        redirect_to new_exam_path
      else
        redirect_to @account.user
      end
    else
      render :new
    end
  end

  def update
    if @account.update(account_params)
      redirect_to :back, notice: "Your account has been updated successfully."
    else
      render :edit
    end
  end

  private

    def account_params
      params.require(:account).permit(:name, :subdomain)
    end

    def set_account
      @account = Account.find_by(user_id: current_user.id)
    end
end

app/helpers/accounts_helper.rb
# == Schema Information
#
# Table name: accounts
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  subdomain  :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

module AccountsHelper
end

app/views/accounts/_form.html.erb
<div class="jumbotron writing no-padding">
  <div class="container">
  </div>
</div>

<h1>Your Subdomain at OakrootAssessments</h1>

<div class="row">
  <div class="well col-sm-8 col-md-offset-2">

    <%= form_for(@account, url: accounts_path(creating_test: @creating_test), method: :post) do |f| %>

      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :subdomain %><br>
        <%= f.text_field :subdomain, autofocus: true, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Next", class: "btn btn-success btn-lg col-xs-12" %>
      </div>
    <% end %>

  </div>
</div>

app/views/accounts/new.html.erb
<%= provide(:title, "Create a Subdomain") %>

<%= render 'form' %>